$crypto-key-type-choice /= #6.32780(bytes .size 48)

digest = [
  alg: (int / text),
  val: bytes
]

non-empty<M> = (M) .and ({ + any => any })

$$flags-map-extension //= &(
  sevsnpvm-policy-smt-allowed: -1,
  sevsnpvm-policy-migration-agent-allowed: -2,
  sevsnpvm-policy-debug-allowed: -3,
  sevsnpvm-policy-single-socket-only: -4,
  sevsnpvm-policy-cxl-allowed: -5,
  sevsnpvm-policy-mem-aes-256-xts-required: -6,
  sevsnpvm-policy-rapl-must-be-disabled: -7,
  sevsnpvm-policy-ciphertext-hiding-must-be-enabled: -8,
  sevsnpvm-policy-reserved: -47..-9,
)

$version-scheme /= &(sevsnpvm-familyimageid-hex: -1)

$raw-value-type-choice /= uint

$$flags-map-extension //= &(
  sevsnphost-smt-enabled: -49,
  sevsnphost-tsme-enabled: -50,
  sevsnphost-ecc-mem-reported-enabled:-51,
  sevsnphost-rapl-disabled: -52,
  sevsnphost-ciphertext-hiding-enabled: -53
  sevsnphost-reserved: -112..-49
)

svn-type = uint
svn = svn-type
min-svn = svn-type
tagged-svn = #6.552(svn)
tagged-min-svn = #6.553(min-svn)
svn-type-choice = tagged-svn / tagged-min-svn

uint16 = 0..65535

uint32 = 0..4294967295

uint64 = 0..18446744073709551615

