tagged-uint8 = #6.64(bytes1)
tagged-leuint32 = #6.70(bytes4)
tagged-leuint64 = #6.71(bytes8)
tagged-bytes4   = #6.560(bytes4)
tagged-bytes8   = #6.560(bytes8)
tagged-bytes32  = #6.560(bytes16)
tagged-bytes32  = #6.560(bytes32)
tagged-bytes64  = #6.560(bytes64)
bytes1  = bytes .size 1
bytes2  = bytes .size 2
bytes4  = bytes .size 4
bytes8  = bytes .size 8
bytes16 = bytes .size 16
bytes32 = bytes .size 32
bytes48 = bytes .size 48
bytes64 = bytes .size 64
